name: Crear archivo JSON con secreto

on:
  push:
    branches:
      - main

jobs:
  crear-archivo-json:
    runs-on: ubuntu-latest

    steps:
      - name: Crear archivo JSON con secreto
        env:
          BUCKETGCP: ${{ secrets.BUCKETGCP }}
        run: echo 'Allan capito del mundo mundial' > secret.json

      - name: Guardar archivo JSON como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: secret.json
