name: bigquery

on:
  push:
    branches:
      - main
  schedule:
    - cron: '40 21 * * MON-FRI'   # Ejecutar a las 18:15 de lunes a viernes

jobs:
  ejecutar-script-de-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Instalar dependencias
      run: |
        pip install pandas google-auth pandas-gbq gcsfs

    - name: Crear archivo de credenciales JSON
      run: |
        echo '{
  "type": "service_account",
  "project_id": "automatizacion-taxis-nyc",
  "private_key_id": "2ddcc1ed9bce99b427c2b451aa0c3d63b1e39c51",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCxKKiLczdaG8H7\nm9XlWKNqM+sRbwFI2gtQFClPJWNsjAoBe/W8GLvr7Q3CJ6iwAW7tku6ohJyawD6R\nDkBiaM5RCSqo8SgWgZGcWb86HmF1GT10OFiZETqnxy/D7LL8e754YFy48Pp7S2qM\n9xeAqZhh8qJnMpb8b3UstizansviV6Dn33iB1EiSZ+pDhsll4KzZwd3V0ewt/uga\nQjWLhKWoKKAdEMSUMy+eUqZOA309cXnZYVNlMpOpXUgl8braLo2yUSyicbcJVaL5\nLY8YqtAwlgmVFDpM3bIZJ02V0b2o6SCZrZ0jAFdMluv3yWML1TsT/2ffo48Bz6GS\nBASbTkevAgMBAAECggEACNhG0e+Gq/EG1lEJdNHgFsVQzyYDomeAeRcImPL868Zy\nGXDe6+0wNK85KKBiQ6dOqn3TfIZiazd96DAV9tPUuScEAjtIDRea9XtlmLk7lGUW\nNF87zSiXDRlcwSNoLELhV5E4D+O4Hb++KhuMCNhuyzUZ9p0H/MJzzy+pPaD//OTd\nwzJaJBZRgpGlRdJMvsbravkgLIqrrmF700Lg5TmlwbknfMRF73MKakWxamarB0AB\naSHsKyjJImWDXndxh/MXJtXqXZwOQjQMlD/RmqjP18v4waU2i5MZIUyhFX9x0FTE\ngL9hsdo+u39PnSqR1Se16HsIzmD9zuSsAb0Ju6iUwQKBgQDoWg/Cpy84UzzidX61\nEwhgUJvMrtuZu7NqUoYLn0Lm1qBqCH5FH/e/wEiJvLsawCGQbvC1aWZHLAJOrk8E\nXYFuR5OapYsyUgh/n+vab6ESule0/3p9xJBI1GLl8AinjXyY0ztzhjTT1qKk+eqJ\n20DfYBeEGffjumgVOuKjhoxGHQKBgQDDMIpxIBXqn0/40xKE54bCD12HAc9/biKi\nVoukmC9cSSra2/INPvPvw74WTQ0freV0R8DyFbLtGfC+UdxMIO5J1B++xzHzo7ej\no2WNCJ1CvAw2uhAFE8DWdcOXrUFQ9frcd+cEljpBSksJTTDr/SIzoQ34URwBqhr1\nnmc11pxrOwKBgCbtj95o7Dxflb/LN6NWwPyCBNhSI3CqRfD2Sob/89GA+/dH3P/v\nzy5NJNoOyLo+nmD4dVOviPc7pFdSVOLCV8EGNPCf86ZGoC3huT4rnazpk3A7rWYM\n3K+XBcrIYGrSBaIFIdzFC2zCdRV22ZinJ0NFcisrvqBkxrNn3jjPfgjxAoGASvI8\nditnvurk/hmtprJvn9vegZREZB2Z1tN8UvrMVJcTiW2ih0uAxrNWLaHwRBW1YOyc\nPVfvl/K56ZntCJ4sYNS+S7aYi4B1ZrO6rmh8Wb9ywSC4PfrTtIULURYJWljYtgak\nAbLdM2yfWzb0beiIVWKlxo7+PfVe3Kix4I5DCTkCgYBt3R+wMNkkirgTob9JlpWB\nBCS+a6wqBUX6fSjx5yScTNz/GYQT4Cx96GsuQSgI0fSHTMwZRCAXHDfyHWFn/AMX\nD16VwAG68fQmNN1JhpyvNYiH6ja3jD5VMXqGq+73DlFMR6Q4tUwoeXm3zoxUijOo\nWBveGmLRDI8DRzeAYh+UvQ==\n-----END PRIVATE KEY-----\n",
  "client_email": "cloudstorage@automatizacion-taxis-nyc.iam.gserviceaccount.com",
  "client_id": "104343921881522348990",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/cloudstorage%40automatizacion-taxis-nyc.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}'
    - name: Ejecutar script de Python
      run: |
        python Automatizado.py
