name: Crear archivo JSON con secreto y ejecutar Automatizado.py

on:
  push:
    branches:
      - main

jobs:
  crear-archivo-json-y-ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Crear archivo JSON con secreto
        run: echo "{\"GCP_BUCKET\": \"${{ secrets.GCP_BUCKET }}\"}" > secret.json

      - name: Guardar archivo JSON como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: secret.json

      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: |
          pip install pandas google-auth pandas-gbq gcsfs

      - name: Descargar archivo JSON con secreto
        uses: actions/download-artifact@v2
        with:
          name: secret
          path: .

      - name: Ejecutar script de Python
        run: |
          python Automatizado.py
